version: "3.3"

services:
  test-app-nginx:
    image: 'nginx:stable-alpine'
    container_name: test-app-nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  test-app-mysql:
    image: mysql:8.0.24
    user: "${UID}:${GID}"
    container_name: test-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker-configs/mysql:/var/lib/mysql/
  phpmyadmin:
    depends_on:
      - test-app-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      PMA_HOST: test-app-mysql
      MYSQL_ROOT_PASSWORD: root
  test-app-app:
    build: 
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: test-app-app
    volumes:
      - ./:/var/www/html